</main>
    <footer class="text-center text-white py-3">
        <div class="container">
            <!-- The year is now dynamic and will always show the current year -->
            <p class="mb-0">&copy; <?php echo date('Y'); ?> SKILLSWAP. ALL RIGHTS RESERVED. | Coded by s4150225</p>
        </div>
    </footer>

    <!-- Bootstrap 5 JS Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
    <!-- Custom JS -->
    <script src="assets/js/scripts.js"></script>
</body>
</html>